services:
  # Spring Boot Application
  spring-boot-app:
    image: backend
    ports:
      - "8091:8091"  # Correction de la syntaxe des ports
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/api_etudiant
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql  # Correction de la syntaxe de "depends_on"

  # MySQL Database
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'api_etudiant'  # Correction de la syntaxe des variables d'environnement
      MYSQL_ROOT_USERNAME: 'root'  # Modification de MYSQL_ROOT_USERNAME à MYSQL_ROOT_PASSWORD
      MYSQL_ROOT_PASSWORD: 'root'  # Modification de MYSQL_ROOT_USERNAME à MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"  # Correction du format des ports
    volumes:
      - api_etudiant:/var/lib/mysql  # Correction du nom du volume (pas d'espace)

# Liste des volumes
volumes:
  api_etudiant:  # Correction du nom du volume (pas d'espace)
